### ISSUE TITLE
Duplicate entries on rotate

### ISSUE THREAD

**Issue by AAverin** [roughike/BottomBar#222]
At the moment I'm am doing
```
bottomBar = BottomBar.attach(baseActivity, savedInstanceState)
        bottomBar.setItemsFromMenu(R.menu.main_bottom_menu, this)
```
in `onCreate`.
What would be the right place to set items to make sure there is duplicate BottomBar after device was rotated?

**Comment by Xstar97** [comment]
I never came across this issue however only when with implementing badges, but here is an easy fix for your solution!
add the following to the activity thats hosting bottombar in your manifest
android:configChanges="orientation|screenSize"

what does it do?
If you rotate your device it wont reload & hopefully wont caused the same issue again!

**Comment by AAverin** [comment]
@Xstar97 this is not a solution
`android:configChanges="orientation|screenSize"`
only means that you take responsibility handling these kinds of config changes yourself if your activity, and I don't want to do this.

**Comment by Xstar97** [comment]
did you try this too?
@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        mBottomBar.onSaveInstanceState(outState);
    }
both are a solution for me as I(AND you) dont have to actually handle android:configChanges="orientation|screenSize"...so when you rotate the activity...it doesn't reload nor do the fragments reset
if you dont believe me try it yourself

**Comment by Xstar97** [comment]
Like I said before..I ran into a similar problem & when I implemented what I just told you...my recyclerview, fragment, nor activity didnt reset after rotating the device....also are you programmatically creating tabs or doing it from a menu xml?

**Comment by charlesdurham** [comment]
@Xstar97 

`android:configChanges="orientation|screenSize"` isn't solving the problem, it just hides it. You'll still have issues if the OS kills your activity, you can test these scenarios by enabled the "destroy activity" developer option.

**Comment by Xstar97** [comment]
@charlesdurham 
I have a shield tv & a kyocera..dont have those options
@AAverin 
But, how are you fully implementing this library & for which SDK version
since it works completely well on my shield TV, but had to jump through hoops to solve my issue #230

**Comment by shenck** [comment]
So I just ran across a similar issue using the BottomBar library with FragNav.  After the activity was destroyed and re-created, the old fragment would be created along side the new one.  Weird stuff.  I solved the issue by keeping a reference to all my base fragments from the Activity onCreate method and then looping through them and removing them with the fragmentManager in the onSaveInstanceState method...  Like below

`@Override
    protected void onSaveInstanceState(Bundle outState) {

        //remove all the fragments so they don't hang around on re-creation...
        //must be done before onSaveInstanceState
        for( Fragment frag : baseFragments ) {
            getSupportFragmentManager().beginTransaction().remove( frag ).commit();
        }

        super.onSaveInstanceState(outState);

        mBottomBar.onSaveInstanceState(outState);
    }`
