### ISSUE TITLE
Bottom bar falls to low behind the navigation bar

### ISSUE THREAD

**Issue by BenoitDuffez** [roughike/BottomBar#265]
I'm sure I did something wrong but I can't figure out what.

I have this XML:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    android:id="@+id/main_coordinator_layout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".app.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:animateLayoutChanges="true"
        android:fitsSystemWindows="true">
...
    </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/main_fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

    <android.support.design.widget.FloatingActionButton ... />

</android.support.design.widget.CoordinatorLayout>
```

This is the code I use:

```
CoordinatorLayout coordinatorLayout = (CoordinatorLayout) findViewById(R.id.main_coordinator_layout);
mBottomBar = BottomBar.attachShy(coordinatorLayout, findViewById(R.id.main_fragment_container), savedInstanceState);
final OnMenuTabClickListener listener = new OnMenuTabClickListener() {
    @Override
    public void onMenuTabSelected(@IdRes int menuItemId) {
        displayFragment(menuItemId, null);
    }

    @Override
    public void onMenuTabReSelected(@IdRes int menuItemId) {
        // The user reselected item number one, scroll your content to top.
    }
};
mBottomBar.setItemsFromMenu(R.menu.bottom_tab_bar, listener);

mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
mBottomBar.mapColorForTab(1, 0xFF5D4037);
mBottomBar.mapColorForTab(2, "#7B1FA2");
mBottomBar.mapColorForTab(3, "#FF5252");
```

This is the result I get:

![result screenshot](https://cloud.githubusercontent.com/assets/802209/15691384/a5cf424c-2788-11e6-9c19-d64b3496d407.png)

I have tried all combinations of `noTopOffset`, `noNavBarGoodness`, `fitsSystemWindows`... I can't get the bottom bar to be:

* shy
* over the transparent navigation bar

Note that this has been taken with a Nexus 5X running N.

**Comment by RatHN** [comment]
It's silly, but... Have you tried setting a bottom padding for the CoordinatorLayout?

**Comment by BenoitDuffez** [comment]
I haven't. But that's kind of hackyand, also not all devices have a navigation bar, so I would like know which padding to put.
Also, the size is correct when not shy.

**Comment by RatHN** [comment]
Oh... You're right... Wish I could delete that comment... XD

Try to sorround your fragment with a NestedScrollView.

Tomorrow I'm going to try your code and check if happens the same.
Have you tried on other version of Android? This could be a new issue with N

**Comment by BenoitDuffez** [comment]
My fragment is inserted inside the `FrameLayout` and it's not always scrollable. Sometimes it's a `ViewPager`, sometimes a `NestedScrollView`, sometimes a custom view... I can't wrap the `FrameLayout` in a `NestedScrollView`, it would break everything. (unless I am mistaken)

**Comment by RatHN** [comment]
The documentation is clear...
For the bar to be shy you need to give it a nested scroll...
So, you have to wrap the FrameLayout within a NestedScrollView and give that nested scroll as the second parameter on the .shy() function

**Comment by BenoitDuffez** [comment]
There's a `NestedScrollView` inside the `FrameLayout`. I can't have this:
```
<NestedScrollView>
    <FrameLayout>
        <NestedScrollView />
    <FrameLayout>
<NestedScrollView>
```

Right?

**Comment by rgocal** [comment]
I have this problem to.  Im only left to create a dark navigation theme similar to Google Plus to make it look attractive. Watching this for a solution as I have found a solution yet.

**Comment by RatHN** [comment]
As you stated on your original XML, is wrongly implemented. The content that's going to be scrollable (your FrameLayout) have to be inside the NestedScrollView and the BottomBar has to be attached to that NestedScrollView somehow, that way the BottomBar knows when to hide and appear.

**Comment by BenoitDuffez** [comment]
OK thanks a lot for your feedback @RatHN.
Now I am puzzled, I don't know how can I switch fragments if I don't use a `FrameLayout`. How can I have non scrolling fragments if I _need_ to nest everything inside a `NestedScrollView`?

**Comment by RatHN** [comment]
No, @BenoitDuffez,  you can always use your FrameLayout as always, just inside the NestedScrollView. 
So inside onMenuTabReSelected() you can get hold of thr FrameLayout and use a FragmentTransaction to replace the content of your FrameLayout (I think that's what you already have on your display fragment() function)

Does it make it clearer?

**Comment by RatHN** [comment]
This is an implementation of mine
```
mBottomBar.setOnTabClickListener(new OnTabClickListener() {
            @Override
            public void onTabSelected(int position) {
                fragmentTransaction = getSupportFragmentManager().beginTransaction();
                switch (position) {
                    case 0:
                        placeHolderFragment = PlaceHolderFragment.newInstance(1);
                        fragmentTransaction.replace(R.id.frameLayout, placeHolderFragment);
                        fragmentTransaction.commit();
                        break;
                    case 1:
                        placeHolderFragment = PlaceHolderFragment.newInstance(2);
                        fragmentTransaction.replace(R.id.frameLayout, placeHolderFragment).commit();
                        break;
                    case 2:
                        mBottomBar.selectTabAtPosition(0, true);
                        fab.callOnClick();
                        break;
                }
            }

            @Override
            public void onTabReSelected(int position) {
            }
        });
```

As you see, I call a transaction and replace theFragment with another brand new fragment I generate there. You can go fancy and store your fragments on memory and just replace them without generate them again. Or whatever your heart desires :)

**Comment by BenoitDuffez** [comment]
Here's what I did:

```
<android.support.v4.widget.NestedScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="@dimen/global_layout_padding">
    <FrameLayout
        android:id="@+id/main_fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
</android.support.v4.widget.NestedScrollView>
```

This breaks everything.

Could you share your XML?

**Comment by RatHN** [comment]
```
 <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_marginTop="?attr/actionBarSize"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/frameLayout"/>

    </android.support.v4.widget.NestedScrollView>

```
And on the activity:
```
mBottomBar = BottomBar.attachShy((CoordinatorLayout)findViewById(R.id.main_content),
                findViewById(R.id.myScrollingContent),
                savedInstanceState);
```

**Comment by BenoitDuffez** [comment]
This breaks the scrolling behavior and doesn't fix the bottom bar being too low.

**Comment by RatHN** [comment]
Then, I think were facing a mayor problem,..
Sorry dude, that's all I have.

**Comment by BenoitDuffez** [comment]
Thanks for your help.

**Comment by RatHN** [comment]
Hey are you still trying?
Have you tried with fitsSystemWindows set to false?

**Comment by BenoitDuffez** [comment]
It works but it doesn't go behind the navigation bar, which I want it to.

**Comment by rgocal** [comment]
I gave up on this and just made the navbar and bottombar the same color in style.

**Comment by MarcusWolschon** [comment]
" you can always use your FrameLayout as always, just inside the NestedScrollView"
Wrong.
e.g. if the fragment that is inside the FrameLayout contains a SwipeRefreshLayout+Floating Action Button(other ticket here) + RecyclerView = a very common combination,
the addition of the NestedScrollView is not transparent and breaks everything.

Not having the NestedScrollView works for hiding the BottomBar but doesn't work for the interaction between sliding-in bottom bar and the FAB (not) sliding upwards accordingly.

**Comment by BenoitDuffez** [comment]
Correct.
Also for the time being, I did what @rgocal did.

**Comment by MarcusWolschon** [comment]
Aparently any Behavior for a FAB is not loaded if the FAB is not a direct part of the CoordinatorLayout -Layout but loaded later and indirectly by being part of the layout of a fragment.

**Comment by BenoitDuffez** [comment]
This issue isn't about a FAB

**Comment by roughike** [comment]
This should be fixed in the newest version.

[Check the README how to do it](https://github.com/roughike/BottomBar#how-do-i-hide-it-automatically-on-scroll).

**Comment by stepansanda** [comment]
@roughike I still have the same problem on newest version 2.0.1 The bottom bar is scrolled down but it is still visible under the transparent NavBar. I set the behavior like this: `app:bb_behavior="shifting|shy|underNavbar"` and nothing helps me to hide it completely.

**Comment by ognev-zair** [comment]
Solution for me is call method **noNavBarGoodness();**

Prevent the BottomBar drawing behind the Navigation Bar and making it transparent. Must be called before setting items.

**Comment by Mitul1221** [comment]
Which version are you saying?

**Comment by ognev-zair** [comment]
I'm using version 1.3.9

**Comment by Mitul1221** [comment]
I am using 1.4.0.1

**Comment by Mitul1221** [comment]
![aaa](https://cloud.githubusercontent.com/assets/20948807/19489533/3e0878ee-9589-11e6-9b46-693109a31815.jpg)
Check please.


        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.noTopOffset();
        mBottomBar.useFixedMode();
        mBottomBar.setItems(R.menu.menu_bottom);

**Comment by Mitul1221** [comment]
If I remove top offset then bottom side is ok but space is left on top side.

Nexus 5 issue.

**Comment by ognev-zair** [comment]
Try to use the latest version (currently 2.0.2)
In this version this bug was fixed.
