### ISSUE TITLE
Infinity Loop on Startup

### ISSUE THREAD

**Issue by T0bbes** [roughike/BottomBar#287]
Hi,

i don't know if it is my fault but let me try to explain.
I have three main activities and every activity should use these BottomBar. Therefore i have a "BaseActivity".

At the first start the method `onMenuTabSelected`is called. At this place an infinity loop is created. 
Is this my faut (I think so.. :))?
https://gist.github.com/T0bbes/563b681fe2155476af4574b08fd29ea9
Thanks!

**Comment by alexwalterbos** [comment]
It's probably better to use `Fragments` instead of `Activities`, and instead just use one `MainActivity` which has a single `FrameLayout` which you use to put the fragments in. Something like this: 

`activity_main.xml`:
```
<LinearLayout
		xmlns:android="http://schemas.android.com/apk/res/android"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		>
	<!-- This nesting is necessary because you'll be attaching the BottomBar to the LinearLayout and putting the Fragments in the FrameLayout -->
	<FrameLayout
			android:id="@+id/container"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			/>
</LinearLayout>
```

Part of `MainActivity.java`:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);

	navBar = BottomBar.attach(this, savedInstanceState); // navBar is a field of MainActivity
	navBar.setItems(R.menu.bottom_bar);
	navBar.setOnMenuTabClickListener(this);
}

@Override
public void onMenuTabSelected(@IdRes int menuItemId) {
	switch (menuItemId) {
		case R.id.x:
			replaceFragment(XFragment.newInstance());
			break;
		case R.id.y:
			replaceFragment(YFragment.newInstance());
			break;
		case R.id.z:
			replaceFragment(ZFragment.newInstance());
			break;
	}
}

private void replaceFragment(Fragment fragment) {
	getFragmentManager()
		.replace(R.id.container, fragment, yourTagForThisFragment)
		.commit();
}
```

HTH

**Comment by roughike** [comment]
Fixed in the newest version, thanks to @xizzhu !

**Comment by T0bbes** [comment]
@alexwalterbos
Thanks but the discussion whether I use fragments or activities is a differente theme.Rather a religious theme... ;)

@roughike 
Is the fix in version 1.3.8? I still have the problem :/

**Comment by TonyHaddad91** [comment]
This issue isn't fixed yet
